# Havi Random

In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
#warnings.filterwarnings('ignore')
%matplotlib inline  

### Optimization 
from scipy.optimize import brute
from scipy import optimize
import scipy.optimize as opt  

### Cluster 
from sklearn.mixture import GaussianMixture
from sklearn.model_selection import StratifiedKFold
from sklearn.naive_bayes import GaussianNB
from mpl_toolkits.mplot3d import Axes3D
from sklearn.cluster import KMeans
from sklearn import datasets
from sklearn.metrics import silhouette_samples, silhouette_score


## Graph
import plotly.graph_objs as go
from plotly import tools
import plotly.plotly as py
import plotly
loca_path = './'

### Reading the DC Volume and Items data

In [8]:
DC_Volume = pd.read_excel(loca_path+"START HERE_DC Volumes with Case Attributes.xlsx")
items = pd.read_excel(loca_path+"START HERE_DC Volumes with Case Attributes.xlsx", sheetname=1)

ImportError: Install xlrd >= 0.9.0 for Excel support

In [6]:
items.head()

Wrin Prefix   D          F   R  Rank
0         00004-FRENCH FRIES NaN  2176482.0 NaN   1.0
1      00407-CHICKEN NUGGETS NaN   757977.0 NaN   2.0
2      00005-10/1 BEEF PATTY NaN   652402.0 NaN   3.0
3          00070-HASH BROWNS NaN   648789.0 NaN   4.0
4  02813-READY MADE BISCUITS NaN   438040.0 NaN   5.0

In [7]:
DC_Volume.head(1)


Supplier Parent Name  Supplier WSI#  DC Receipts Cases Received  \
0         MCCAIN FOODS          47883                      728707   

          Wrin Prefix                  Wrin Description Wrin Temp Zone  \
0  00004-FRENCH FRIES  00004849-FRIES/440 NATURAL F16/6              F   

   WW Case Height  WW Case Length  WW Case Width WW Weight UOM  \
0            13.5           16.38          13.13            LB   

  WW Pallet TI x HI  WW Gross Weight (LBS) WW Case Dimensions (inches)  DC ID  
0       9.00 x 6.00                   38.0       16.38 x 13.13 x 13.50      7

In [8]:
DC_Volume.columns

Index(['Supplier Parent Name', 'Supplier WSI#', 'DC Receipts Cases Received',
       'Wrin Prefix', 'Wrin Description', 'Wrin Temp Zone', 'WW Case Height',
       'WW Case Length', 'WW Case Width', 'WW Weight UOM', 'WW Pallet TI x HI',
       'WW Gross Weight (LBS)', 'WW Case Dimensions (inches)', 'DC ID'],
      dtype='object')

### Change L, W and H ranking from high to low

In [16]:
l = DC_Volume.apply(lambda row: max(row['WW Case Length'], row['WW Case Width'], row['WW Case Height']), axis=1)
h = DC_Volume.apply(lambda row: min(row['WW Case Length'], row['WW Case Width'], row['WW Case Height']), axis=1)
w = DC_Volume['WW Case Length'] + DC_Volume['WW Case Width'] + DC_Volume['WW Case Height'] - l - h

In [ ]:
DC_Volume['WW Case Length'] = l
DC_Volume['WW Case Width'] = w
DC_Volume['WW Case Height'] = h

## Select temperature zoon

In [9]:
df_F = DC_Volume[DC_Volume['Wrin Temp Zone']=='F']

In [152]:
top_15_inF = items[items.F.notnull()][items.Rank.notnull()]['Wrin Prefix'];
df_F = df_F[df_F['Wrin Prefix'].isin(top_15_inF)];

C:\Program Files\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: UserWarning:

Boolean Series key will be reindexed to match DataFrame index.



In [11]:
df_F = DC_Volume[DC_Volume['Wrin Temp Zone']=='F']

## Cluster to pick the Size



In [12]:
def space_coef(input_size,*param):
    in_val = space_coef_input(input_size,*param)
    out_val  = space_coef_outbound(input_size,*param)
    return -(in_val**2 + out_val**2)**0.5

In [13]:
##  Maximum volume efficiency
#def space_coef(input_size,pallet ='O'):
def space_coef_input(input_size,*param):
    ## Define the pallet
    height,length,width = input_size
    pallet ='O'
#     if params:
#         pallet = params
#     else:
#         pallet = 'O'
        
    coef = 0
    if pallet == 'O':# height ,weight,length for pallet
        Hp = 100
        Lp = 48
        Wp = 40
    else:
        Hp = 100
        Lp = 42
        Wp = 29
    vol_case = height*length*width
    num_H = np.floor(Hp/height)
    num_L = np.floor(Lp/length)
    num_W = np.floor(Wp/width)
    coef = num_H*num_L*num_W*(vol_case)/(Hp*Lp*Wp)
    # since all the optimization function I can find so far is about to find minimum value, 
    # that's the most easy way to get the value right...
    return -coef
    

In [14]:
##  Maximum volume efficiency
#def space_coef(input_size,pallet ='O'):
def space_coef_outbound(input_size,*param):
    ## Define the pallet
    height,length,width = input_size
    pallet ='I'
#     if params:
#         pallet = params
#     else:
#         pallet = 'O'
        
    coef = 0
    if pallet == 'O':# height ,weight,length for pallet
        Hp = 100
        Lp = 48
        Wp = 40
    else:
        Hp = 100
        Lp = 42
        Wp = 29
    vol_case = height*length*width
    num_H = np.floor(Hp/height)
    num_L = np.floor(Lp/length)
    num_W = np.floor(Wp/width)
    coef = num_H*num_L*num_W*(vol_case)/(Hp*Lp*Wp)
    # since all the optimization function I can find so far is about to find minimum value, 
    # that's the most easy way to get the value right...
    return -coef

In [15]:
#brief create interval for the matrix, want to use 0.2 inch as an unit.
#input mat it should be np.array, n x 3 matrix
#input
#Return:   2 element list, lower bound,  upeper bound
def UpLowbound_gen(mat,limit = 'vol'):
    pect_ = 1.1 # 10% increase or decreaase
    unit = 1/0.2
    if limit =='vol':
        pect_ = pect_ ** (1. / 3)

    else:
        pect_ = pect_
        
    upper_mat = np.multiply(mat,pect_)
    upper_mat = np.divide(np.floor(np.multiply(upper_mat,unit)),unit)
    lower_mat = np.around(np.divide(mat,pect_),decimals=2)
    lower_mat = np.divide(np.ceil(np.multiply(lower_mat,unit)),unit)
    return lower_mat, upper_mat,np.dstack([lower_mat,upper_mat])

### Kmeans Cluster  Create

K-means to get new cluster

In [16]:
from sklearn import svm
from sklearn.covariance import EllipticEnvelope
from sklearn.ensemble import IsolationForest
from sklearn.neighbors import LocalOutlierFactor

In [88]:
def cluster_outlier(df):
    n_samples = df_F.shape[0]
    # define two outlier detection tools to be compared
    clf = svm.OneClassSVM(nu=0.05, kernel="rbf", gamma=0.1)
    clf.fit(df)
    ls_outlier = clf.predict(df)
    return ls_outlier

In [135]:
def outlier_marker(df,k):
    for i in range(k):
        ls_outlier_result = cluster_outlier(df[df['class'] == i].iloc[:,0:3])
        ls_index = df[df['class'] == i].index
        for j in range(len(ls_outlier_result)):
            if ls_outlier_result[j] == -1:
                df.loc[ls_index[j],['class']] = -1
    return df
        

In [153]:
X_train = df_F.loc[:,['WW Case Height','WW Case Length', 'WW Case Width']]

elbow method for getting the number of clusters

### silhouette_score for Picking Cluster number
~~~ modified by grid search. later.

In [51]:
def silhouette_score_cluster_num(df):
    ls_sil = list()
    for i in range(2,int(len(df)/2)):
        kmean_estimators  = KMeans(n_clusters=i)
        kmean_estimators.fit(X_train)
        labels = kmean_estimators.labels_
        score = silhouette_score(df, labels, metric='euclidean')
        ls_sil.append(score)
    return np.argmax(ls_sil)-1

### Pick the best K from silhouette_score
K number dcided by solhoutte number


In [71]:
k = silhouette_score_cluster_num(X_train);k

In [154]:
kmean_estimators  = KMeans(n_clusters=k)
kmean_estimators.fit(X_train)
labels = kmean_estimators.labels_
X_train['class'] = labels

In [155]:
X_train = outlier_marker(X_train,k);

### Plot 3-D graph

In [78]:
def color_gen(num):
    ls_color =list()
    for i in range(num):
        ls_color.append("rgb({0:d},{1:d},{2:d})".format(int(np.random.uniform(128,255,1)),int(np.random.uniform(0,255,1)),int(np.random.uniform(0,255,1))))
    return ls_color

In [141]:
data = []
clusters = []
colors = color_gen(k)
for i in range(k):
    color =  colors[i]
    dx = X_train[X_train['class'] == i].iloc[:, 0],
    dy = X_train[X_train['class'] == i].iloc[:,  1],
    dz = X_train[X_train['class'] == i].iloc[:,  2],
    x = dx[0]
    y = dy[0]
    z = dz[0]
    trace = go.Scatter3d(
        x = x, y = y, z = z,   
        mode = 'markers',
        marker = dict( size=10, color=color, line=dict(width=0) ) )
    data.append( trace )

color =  'rgb(0,0,0)'
dx = X_train[X_train['class'] == -1].iloc[:, 0],
dy = X_train[X_train['class'] == -1].iloc[:,  1],
dz = X_train[X_train['class'] == -1].iloc[:,  2],
x = dx[0]
y = dy[0]
z = dz[0]
trace = go.Scatter3d(
    x = x, y = y, z = z,   
    mode = 'markers',
    marker = dict( size=10, color=color, line=dict(width=0) ) )
data.append( trace )


layout = go.Layout(
    title='Plot Title',
    xaxis=dict(
        title='x Axis',
        titlefont=dict(
            family='Courier New, monospace',
            size=18,
            color='#7f7f7f'
        )
    ),
    yaxis=dict(
        title='y Axis',
        titlefont=dict(
            family='Courier New, monospace',
            size=18,
            color='#7f7f7f'
        )
    )
)
fig = go.Figure(data=data, layout=layout)
plotly.offline.plot(fig, filename='simple-3d-scatter.html')

'file://C:\\Users\\csblo\\Documents\\Math565\\HAVI\\RD_HAVI\\simple-3d-scatter.html'

## Generate Case new size

In [158]:
## to get the H,L,W range. 
kmean_estimators.cluster_centers_= X_train.iloc[:,0:3] ## Put the all data into optmize
Lmat,Umat ,ULmat = UpLowbound_gen(kmean_estimators.cluster_centers_)
ideal_input_size = list()
for limit in ULmat:
    H_MinMax, L_MinMax, W_MinMax = limit
    rranges = (slice(H_MinMax[0],H_MinMax[1], 0.2), slice(L_MinMax[0],L_MinMax[1], 0.2)
           ,slice(W_MinMax[0],W_MinMax[1], 0.2))
    resbrute = brute(space_coef_input, rranges, full_output=True, finish=None)
    ideal_input_size.append(resbrute[0])## ideal size is correspond to original cluster center.

In [159]:
ideal_input_size

[array([ 13.8,  16. ,  13.2]),
 array([ 12.4,  16. ,  13.2]),
 array([ 12.4,  16. ,  13.2]),
 array([ 13.8,  16. ,  13.2]),
 array([ 12.4,  16. ,  13.2]),
 array([  8. ,  19.8,  12. ]),
 array([  8. ,  20.6,  12. ]),
 array([  8. ,  19.8,  12. ]),
 array([  7.6,  20.8,  10. ]),
 array([  8.2,  20.8,  10. ]),
 array([  8.2,  20.8,  10. ]),
 array([  8.4,  16. ,  13. ]),
 array([  8. ,  15.4,  13.2]),
 array([  8.2,  16. ,  13.2]),
 array([  8.2,  16. ,  13.2]),
 array([ 12.4,  16. ,  13.2]),
 array([ 12.4,  16. ,  13.2]),
 array([ 12.4,  16. ,  13.2]),
 array([ 12.4,  16. ,  11.8]),
 array([ 13. ,  16. ,  13.2]),
 array([ 12.4,  15.4,  12.8]),
 array([ 13. ,  16. ,  13.2]),
 array([ 12.4,  16. ,  13.2]),
 array([ 14. ,  16. ,  13.2]),
 array([ 14. ,  16. ,  13.2]),
 array([ 14. ,  16. ,  13.2]),
 array([ 11. ,  18. ,  13.2]),
 array([ 11. ,  18. ,  13.2]),
 array([  9. ,  16. ,  13.2]),
 array([  9.6,  17. ,  13.2]),
 array([ 12.4,  16. ,  13.2]),
 array([ 12.4,  16. ,  13.2]),
 array([

In [150]:
## to get the H,L,W range. 
Lmat,Umat ,ULmat = UpLowbound_gen(kmean_estimators.cluster_centers_)
ideal_size = list()
for limit in ULmat:
    H_MinMax, L_MinMax, W_MinMax = limit
    rranges = (slice(H_MinMax[0],H_MinMax[1], 0.2), slice(L_MinMax[0],L_MinMax[1], 0.2)
           ,slice(W_MinMax[0],W_MinMax[1], 0.2))
    resbrute = brute(space_coef, rranges, full_output=True, finish=None)
    ideal_size.append(resbrute[0])## ideal size is correspond to original cluster center.

ValueError: too many values to unpack (expected 3)

## Understanding the data

### Mismatch of items

In comparing the unique "WRIN PREFIX", the following items are missing from "DC Volumes" and "Xtab-Temp Zone X WRIN" sheets.
1. 00042-DIET COKE SYRUP - with 152,368 cases received
2. 00168-SPRITE DRINK SYRUP - with 142,032 cases received

Both the WRIN PREFIX has temperature zone as Dry with the same Supplier "COCA-COLA COMPANY (THE)/MCDONALDS ACCOUNT GROUP". Adding these two tiems in the "Xtab-Temp Zone X WRIN" sheet will change the rank of other items.

In [ ]:
temperature = ('F', 'R', 'D')
for i in temperature:
    print("Temp zone", i ,"missing:",set(DC_Volume['Wrin Prefix'][DC_Volume['Wrin Temp Zone'] == i].unique()).symmetric_difference(set(items['Wrin Prefix'][items[i].notnull()].unique())))

In [ ]:
print("Total number of items manufactured and distributed:",len(DC_Volume['Wrin Prefix'].unique()), "items")
print("Number of DCs:", DC_Volume['DC ID'].unique())
print("Total number of suppliers:",len(DC_Volume['Supplier Parent Name'].unique()))
print("Freezer items:",len(DC_Volume['Wrin Prefix'][DC_Volume['Wrin Temp Zone'] == "F"].unique()))
print("Dry items:",len(DC_Volume['Wrin Prefix'][DC_Volume['Wrin Temp Zone'] == "D"].unique()))
print("Refrigerator items:",len(DC_Volume['Wrin Prefix'][DC_Volume['Wrin Temp Zone'] == "R"].unique()))

### Wrong Temperature Zone

"LOPEZ FOOD INC" is the only Supplier to pack Beef patty in Temp Zone "R" and sent 105 cases in total. They are also responsible for sending "Canadian Bacon/Natural juice" in Temp Zone "R"

In [ ]:
DC_Volume[(DC_Volume['Wrin Prefix']=='00006-4/1 BEEF PATTY') & (DC_Volume['Wrin Temp Zone']=='R')]

Find the most number of cases sent by a supplier

Why is 1 item measured in KG but the gross weight in LBS. is this typo error?

Check what all items goes to each DCs

### Basic visualization

In [ ]:
#Top and least suppliers for Mcdonalds
#plt.figure()

plt.figure(figsize=(50,20))
plt.subplot(121)

df = DC_Volume[['Supplier Parent Name','DC Receipts Cases Received']]
df['Supplier Parent Name']=df['Supplier Parent Name'].replace(['COCA-COLA COMPANY (THE)/MCDONALDS ACCOUNT GROUP'],value='COCA-COLA MCD')
df['Supplier Parent Name']=df['Supplier Parent Name'].replace(['COCA-COLA COMPANY (THE)/MOTHER PARKERS FOODS LTD'],value='COCA-COLA Mother')
grouped = df.groupby(df['Supplier Parent Name']).sum().reset_index()
grouped = grouped.sort_values('DC Receipts Cases Received', ascending = False)
sns.barplot(grouped['Supplier Parent Name'][:15], grouped['DC Receipts Cases Received'][:15])
plt.title("Top 15 Suppliers",size=50)
plt.ylabel("Cases Recevied by DC",size=40)
plt.xticks(rotation=90,size=30)
plt.yticks(size=30)
plt.xlabel('Supplier Name',size=50)

plt.subplot(122)
sns.barplot(grouped['Supplier Parent Name'][-15:], grouped['DC Receipts Cases Received'][-15:])
plt.title("Least 15 Suppliers",size=50)
plt.ylabel("Cases Recevied by DC",size=40)
plt.xticks(rotation=90,size=30)
plt.yticks(size=30)
plt.xlabel('Supplier Name',size=50)
plt.show()


# DC outbound

In [ ]:
df_outbound = pd.read_excel(loca_path+"DC Sales_DC7.xlsx")

In [ ]:
df_outbound.head(1)

In [ ]:
len(df_outbound['Rest ID'].unique())